baseURL = "https://lbrooke.com/"
languageCode = "en-us"
title = "lbrooke.com"
theme = "diary"

[params]
subtitle = "Hobbies and other stuff"

[taxonomies]
   tag = "tags"

[[menu.main]]
url = "/tags"
name = "Tags"
weight = 1
[[menu.main]]
url = "/index.xml"
name = "RSS Feed"
weight = 2
